export const VALIDAR_FORMULARIO = 'VALIDAR_FORMULARIO';
export const VALIDAR_FORMULARIO_EXITO = 'VALIDAR_FORMULARIO_EXITO';
export const VALIDAR_FORMULARIO_ERROR = 'VALIDAR_FORMULARIO_ERROR';

export const AGREGAR_BATIDO = 'AGREGAR_BATIDO';
export const AGREGAR_BATIDO_EXITO = 'AGREGAR_BATIDO_EXITO';
export const AGREGAR_BATIDO_ERROR = 'AGREGAR_BATIDO_ERROR';

export const COMENZAR_DESCARGAR_BATIDOS = 'COMENZAR_DESCARGAR_BATIDOS';
export const DESCARGA_BATIDOS_EXITOSA = 'DESCARGA_BATIDOS_EXITOSA';
export const DESCARGA_BATIDOS_ERROR = 'DESCARGA_BATIDOS_ERROR';

export const COMENZAR_SUMAR_INGREDIENTES = 'COMENZAR_SUMAR_INGREDIENTES';
export const SUMAR_EXITO = 'SUMAR_EXITO';


